name: Build

on: [push, pull_request]

jobs:
  build-windows-i386:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build windows-i386
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug --32bits
        ./waf.bat build

    - name: Upload artifacts
      uses: actions/upload-artifact@v3.1.3
      with:
          name: Build Version
          path: build
